/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const getEnvVar = (key: string): string => {
  const value = import.meta.env[key as keyof ImportMetaEnv] as string | undefined;
  if (!value) {
    throw new Error(`Missing environment variable: ${key}`);
  }
  return value;
};

export const projectId = getEnvVar('VITE_SUPABASE_PROJECT_ID');
export const supabaseUrl = getEnvVar('VITE_SUPABASE_URL');
export const publicAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY');